# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/ROR.xdc

# Block Designs: bd/ROR_design/ROR_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ROR_design || ORIG_REF_NAME==ROR_design} -quiet] -quiet

# IP: bd/ROR_design/ip/ROR_design_processing_system7_0_0/ROR_design_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ROR_design_processing_system7_0_0 || ORIG_REF_NAME==ROR_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/ROR_design/ip/ROR_design_axi_dma_0_0/ROR_design_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ROR_design_axi_dma_0_0 || ORIG_REF_NAME==ROR_design_axi_dma_0_0} -quiet] -quiet

# IP: bd/ROR_design/ip/ROR_design_axi_smc_0/ROR_design_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ROR_design_axi_smc_0 || ORIG_REF_NAME==ROR_design_axi_smc_0} -quiet] -quiet

# IP: bd/ROR_design/ip/ROR_design_rst_ps7_0_100M_0/ROR_design_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ROR_design_rst_ps7_0_100M_0 || ORIG_REF_NAME==ROR_design_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/ROR_design/ip/ROR_design_smartconnect_0_0/ROR_design_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ROR_design_smartconnect_0_0 || ORIG_REF_NAME==ROR_design_smartconnect_0_0} -quiet] -quiet

# IP: bd/ROR_design/ip/ROR_design_xlconcat_0_0/ROR_design_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ROR_design_xlconcat_0_0 || ORIG_REF_NAME==ROR_design_xlconcat_0_0} -quiet] -quiet

# IP: bd/ROR_design/ip/ROR_design_ROR_IP_0_4/ROR_design_ROR_IP_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ROR_design_ROR_IP_0_4 || ORIG_REF_NAME==ROR_design_ROR_IP_0_4} -quiet] -quiet

# XDC: c:/Users/karta/ROR_FPGA_1/ROR_FPGA_1.gen/sources_1/bd/ROR_design/ROR_design_ooc.xdc
